### ISSUE TITLE
index.rst: layout rules for buffer data are unspecified

### ISSUE THREAD

**Issue by dneto0** [gpuweb/WHLSL#268] opened 2018-11-22 20:43 UTC
In "Arguments and Return Types", it says entry point interfaces can use slices to refer to data in a resource.

> 2. Resources. These must be either the opaque texture types, opaque sampler types, or slices. Slices must only hold scalars, vectors, matrices, or structs containing any of these types. Nested structs are allowed. The packing rules for data inside slices are described below. All resources must be in the device or constant memory space, and use the appropriate semantic as described below.

This is the only mention of "slice" or "packing" in the index.rst doc.

So WHLSL has not specified how to put data into a buffer to pass into a shader.

**Comment by dneto0** [comment] 2018-11-22 20:58
Additionally, the layout of matrices is unspecified.  Are they row major or column major?

The layout of vectors is unspecified.  How big is a float3?  Does it occupy the same space as a float4?

**Comment by litherum** [comment] 2018-11-26 03:33
Duplicate of https://github.com/gpuweb/WHLSL/issues/8

**Closed by litherum** 2018-11-26 03:33 UTC
